name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ github.actor }}" --password-stdin
      - name: Build and Push Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ github.actor }}/rb3.2-apache:latest
          docker push ${{ github.actor }}/rb3.2-apache:latest
